---
title: "ASMNW - Übung 2"
author: "Peter von Rohr"
date: "`r Sys.Date()`"
output: pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Kontrollfrage 1
Weshalb werden in Schritt 1 der genomischen Selektion geschätzte Zuchtwerte anstelle von phänotypischen Beobachtungen verwendet?


## Kontrollfrage 2
Welche Eigenschaft der BLUP-Zuchtwerte führt zu der problematischen Reduktion der Varianz der geschätzten Zuchtwerte im Vergleich zur Varianz der phänotypischen Werte?


## Kontrollfrage 3
Für Schritt 1 der genomischen Selektion wurden folgende Modelle angeschaut:

\begin{tabular}{ll}
wahre Zuchtwerte  &  $\mathbf{g} = \mathbf{1}\mu + \mathbf{M}\mathbf{a} + \mathbf{\epsilon}$ \\
phänotypische Beobachtungen  &   $\mathbf{y} = (\mathbf{1}\mu + \mathbf{X}\mathbf{b}) + \mathbf{M}\mathbf{a} + (\mathbf{\epsilon}+ \mathbf{e})$ \\
geschätzte Zuchtwerte  &  $\hat{\mathbf{g}} = \mathbf{1}\mu + \mathbf{M}\mathbf{a} + (\mathbf{\epsilon} + (\hat{\mathbf{g}} - \mathbf{g}) )$
\end{tabular}

1. Welche Struktur haben diese Modelle
2. Welche Parameterschätzmethode wird üblicherweise für diese Modelle verwendet
3. Wiese kann diese Parameterschätzmethode für die genomische Selektion nicht verwendet werden


## Aufgabe 1: Schätzung der a-Werte aufgrund phänotypischer Leistungen
Der Datensatz `geno_sel_step1.csv` enthält phänotypische Werte in der Kolonne `bwt_sim`. Diese Werte wurden aufgrund von sechs genetischen Loci simuliert. Abgesehen von den genetischen Informationen gibt es auch noch zwei fixe Faktoren, welche mit `sex` und `age` bezeichnet sind. Alle Angaben sind in der gleichen Datei enthalten.

### Ziel
Schätzen Sie für die sechs Loci die entsprechenden `a`-Werte.

### Ihre Aufgaben
Da es sich nur um sechs Loci handelt, können die `a`-Werte mit einer Regression geschätzt werden. Folgende Schritte sollten zum Ziel führen.

1. Einlesen der Daten mit 

```{r ReadInput, eval=FALSE}
dfGenoSelDat <- read.csv2(file = "http://charlotte-ngs.github.io/GELSAM/w10/geno_sel_step1.csv", 
                          stringsAsFactors = FALSE)
```

2. Lineare Regression mit funktion `lm()` wobei die phänotypischen Werte in Kolonne `bwt_sim` gespeichert sind.

3. Anzeige der Resultate mit Funktion `summary()`

Wie gross sind nun die `a`-Werte der sechs Loci?

