\documentclass{scrartcl}

%\usepackage{fancyhdr}

\newcommand{\points}[1]
{\begin{flushright}\textbf{#1}\end{flushright}}

\usepackage{Sweave}
\begin{document}
\input{asmas_w15_exam_sol-concordance}


\thispagestyle{empty}

\titlehead
{
	ETH Z\"urich\\%
	D-USYS\\%
	Institut f\"ur Agrarwissenschaften
}

\title{\vspace{5ex} L\"osungen zur Pr\"ufung \\
       Angewandte Statistische Methoden in den Nutzierwissenschaften\\
       FS 2016 \vspace{3ex}}
\author{Peter von Rohr \vspace{3ex}}
\date{
  \begin{tabular}{lr}
  \textsc{Datum}  & \textsc{\emph{30. Mai 2016}} \\
  \textsc{Beginn} & \textsc{\emph{08:00 Uhr}}\\
  \textsc{Ende}  & \textsc{\emph{08:45 Uhr}}\vspace{3ex}
\end{tabular}}
\maketitle

% Table with Name
\begin{tabular}{p{3cm}p{6cm}}
Name:     &  \\
         &  \\
Legi-Nr:  & \\
\end{tabular}

% Table with Points

\vspace{3ex}
\begin{center}
\begin{tabular}{|p{3cm}|c|c|}
\hline
Aufgabe  &  Maximale Punktzahl  &  Erreichte Punktzahl\\
\hline
1        &  10  & \\
\hline
2        &  13  & \\
\hline
3        &  6  & \\
\hline
4        &  6  & \\
\hline
Total    &  35 & \\
\hline
\end{tabular}
\end{center}

\clearpage
\pagebreak

\section*{Aufgabe 1: Modellierung vor und nach Einf\"uhrung der Genomischen Selektion}
\begin{enumerate}
\item[a)] Wo liegen die Unterschiede im Bezug auf die Modellierung von Tierzuchtdaten vor und nach der Einf\"uhrung der genomischen Selektion (GS) im Bezug auf die folgendne Punkte?
\end{enumerate}
\points{6}

\vspace{5ex}
\begin{tabular}{|l|p{6cm}|p{6cm}|}
\hline
Punkt  &  vor GS  &  nach GS \\
\hline
Informationsquellen   &  ph\"anotypische Leistungen und Pedigree, einzelne Marker
                      &  gleich wie vor GS, zus\"atzlich SNP Information \\ %\vspace{20ex}\\
\hline
statistisches Modell  &  zuerst Vatermodell danach BLUP Tiermodell, Varianzkomponenten mit REML
                      &  einfaches lineares Modell (Regression) Sch\"atzung mit Bayes im zwei-Schritt Verfahren oder mit single-step BLUP \\ %\vspace{25ex}\\
\hline
genetisches Modell    &  Infinitesimalmodell, unendlich viele Gene an unbekannten Orten
                      &  polygenes Modell, endlich viele Gene an bekannten Orten eingegrenzt durch dichte Markerkarten \\ %\vspace{25ex}\\
\hline
\end{tabular}

\clearpage
\pagebreak

\begin{enumerate}
\item[b)] In der genomischen Selektion werden h\"aufig gesch\"atzte BLUP-Zuchtwerte aus einem Tiermodell als Beobachtungen verwendet.
\end{enumerate}

\begin{itemize}
\item Nennen sie je einen Vorteil und einen Nachteil der Verwendung von BLUP Zuchtwerten als Beobachtungen

Vorteil: Verf\"ugbarkeit bei vielen Tieren

Nachteil:  BLUP-Zuchtwerte zeigen aufgrund der Schrumpfung eine verringerte Varianz

\item Welches Verfahren wird verwendet, um den Nachteil von der Verwendung von BLUP-Zuchtwerten als Beobachtungen, zu beheben und nach welchem Prinzip funktioniert dieses Verahren?

Verfahren: Deregression. Multiplikation durch Inverse Genauigkeiten der Zuchtwerte

\end{itemize}
\points{4}


\clearpage
\pagebreak

\section*{Aufgabe 2: Lineare Regression}
Gegeben sind die folgenden Resultate einer linearen Regression
\begin{Schunk}
\begin{Soutput}
Call:
lm(formula = y ~ snp1 + snp2, data = dfSnpData)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.6819  -2.9583   0.1485   2.7452   8.4649 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   0.9661     1.6819   0.574    0.570    
snp1         -2.3806     1.0970  -2.170    0.039 *  
snp2          6.5272     0.9994   6.531 5.28e-07 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.999 on 27 degrees of freedom
Multiple R-squared:  0.6179,	Adjusted R-squared:  0.5896 
F-statistic: 21.83 on 2 and 27 DF,  p-value: 2.286e-06
\end{Soutput}
\end{Schunk}

\begin{enumerate}
\item[a)] Aus welchen Komponenten besteht das lineare Modell?
\end{enumerate}
\points{3}

\noindent\textbf{L\"osung:}
Zielgr\"osse, erkl\"arende Variablen und Resteffekte

\clearpage
\pagebreak

\begin{enumerate}
\item[b)] Wie sieht das Modell aus, welches zu den oben gezeigten Resultaten gef\"uhrt hat?
\end{enumerate}
\points{5}

\noindent\textbf{L\"osung:}
$$ y_i = \beta_0 + \beta_1*snp_{1i} + \beta_2*snp_{2i} + \epsilon_i$$

\clearpage
\pagebreak

\begin{enumerate}
\item[c)] Berechnen Sie aus den oben gezeigten Resultaten das Vertrauensinterval f\"ur die erkl\"arende Variable \verb+snp1+. Wie gross ist die Irrtumswahrscheinlichkeit f\"ur dieses Vertrauensintervall?
\end{enumerate}
\points{3}

\noindent\textbf{L\"osung:}
$$-2.3806 + 1.097 * (-2.170) = -4.76109$$
$$-2.3806 - 1.097 * (-2.170) = -0.00011$$

Die Irrtumswahrscheinlichkeit betr\"agt: $0.039$

\clearpage
\pagebreak

\begin{enumerate}
\item[d)] Wie heisst der folgende Plot und wozu kann dieser Plot verwendet werden?
\end{enumerate}
\points{2}

\includegraphics{asmas_w15_exam_sol-TukeyAnscombePlot}


\noindent\textbf{L\"osung:}
\begin{itemize}
\item Tukey-Anscombe Plot
\item \"Uberpr\"ufung der Modellannahmen (konstante Residuen, lineares Modell korrekt)
\end{itemize}


\clearpage
\pagebreak

\noindent\textbf{Zusatz:} Durch welches Statement wird der oben gezeigte Plot in R erzeugt?

\points{2}

\noindent\textbf{L\"osung:}
\begin{Schunk}
\begin{Sinput}
> plot(fitted(snp_reg), resid(snp_reg))
\end{Sinput}
\end{Schunk}


\clearpage
\pagebreak

\section*{Aufgabe 3: LASSO}

\begin{enumerate}
\item[a)] Was bedeutet die Abk\"urzung LASSO?
\end{enumerate}
\points{1}

\noindent\textbf{L\"osung:} Least Absolute Shrinkage and Selection Operator

\clearpage
\pagebreak

\begin{enumerate}
\item[b)] Sobald in einem linearen Modell die Anzahl Parameter gr\"osser ist als die Anzahl Beobachtungen k\"onnen wir Least Squares nicht verwenden. Was sind in einem solchen Fall Alternativen zu Least Squares?
\end{enumerate}
\points{3}

\noindent\textbf{L\"osung:}
\begin{itemize}
\item Subset Selektion
\item Regularisierung (Shrinkage)
\item Dimensionsreduktion
\end{itemize}

\clearpage
\pagebreak

\begin{enumerate}
\item[c)] Wie unterscheiden sich die Sch\"atzer durch Least Squares vom Sch\"atzer durch LASSO und wie wird die Selektion der Variablen erreicht?
\end{enumerate}
\points{2}

\noindent\textbf{L\"osung:}
\begin{itemize}
\item durch den Strafterm
\item dadurch, dass im Strafterm der Absolutbetrag verwendet wird, werden mit hoher Wahrscheinlichkeit Koeffizienten von gewissen Variablen $0$ gesetzt
\end{itemize}


\clearpage
\pagebreak

\section*{Aufgabe 4: Bayes}

\begin{enumerate}
\item[a)] In welche Kategorien unterteilen Bayesianer die Komponenten eines Modells?
\end{enumerate}
\points{2}

\noindent\textbf{L\"osung:}
bekannte und unbekannte Gr\"ossen

\clearpage
\pagebreak

\begin{enumerate}
\item[b)] Worauf basieren Sch\"atzungen in der Bayes'schen Statistik, aus welchen Komponente besteht das gesuchte Objekt und wie wird dieses berechnet?
\end{enumerate}
\points{3}

\noindent\textbf{L\"osung:}
\begin{itemize}
\item  A posteriori Verteilung der unbekannten gegeben die bekannten Gr\"ossen.
\item  a priori Verteilung, Likelihood und Normalisierungskonstante
\end{itemize}

\begin{eqnarray}
f(\mathbf{\beta}, \sigma^2 | \mathbf{y}) & = & \frac{f(\mathbf{\beta}, \sigma^2, \mathbf{y})}{f(\mathbf{y})} \nonumber \\
                                         & = & \frac{f(\mathbf{y} | \mathbf{\beta}, \sigma^2)f(\mathbf{\beta})f(\sigma^2)}{f(\mathbf{y})}
\label{LinModAPostProb}
\end{eqnarray}


\clearpage
\pagebreak

\begin{enumerate}
\item[c)] Angenommen, Sie haben vor der Sch\"atzung eines Parameters keine Information \"uber den Parameter. Wie lassen Sie diese Tatsache in einer Bayes'schen Analyse einfliessen?
\end{enumerate}
\points{1}

\noindent\textbf{L\"osung:} Uninformative a priori Verteilung

\end{document}
